### ISSUE TITLE
postUpdateDriverPosition(),postBeginRide() not implemented

### ISSUE THREAD

**Issue by tejaslodaya** [david-zhou/UberDriver#1]
If they were not implemented on purpose, then how should I do it? 
Tell me what are the contents to be retrieved from the JSON feed?
Help would be appriciated!

**Comment by david-zhou** [comment]
postBeginRide() should go to a map that guides you to your destination, but destination was not implemented in the UberClient app, so this does nothing. But it is not necessary, as all needed data is stored in the database (distance, time, etc)

postUpdateDriverPosition() is just a method called after updating the driver position in the database, so the client can see the updated position of the Uber in the map in their app. It doesn't need any implementation, but I put the method there just in case I needed it sometime.

**Comment by supersota** [comment]
Hos working
